### PR TITLE
Added readme for rfb project

### LINKED ISSUE #65: Add readme and guidelines to RFB project
### Because

The [role-filler-binding](https://github.com/clamsproject/aapb-annotations/tree/main/role-filler-binding) project contains an empty guidelines.md and an empty README.md. As stated in the [repository README](https://github.com/clamsproject/aapb-annotations/blob/main/README.md) file, we want each subdirectory to contain its own README.md detailing annotation project-specific information (e.g. project name, annotator demographics, annotation environment information, gold generation code dependencies, etc.). Each subdirectory should also contain a guidelines.md with relevant annotation guidelines used in the annotation project.

### Done when

- [ ]  The README.md is updated with relevant information.

- [ ]  The guidelines.md is updated with relevant information.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jarumihooi**
fixes #65

### CODE REVIEW

**Comment by jarumihooi** [comment]
Requesting review of this readme for developing maturity of the project's documentation. Readme should be in a readable state containing up to present information.

**Comment by keighrim** [comment]
Let's wait for 
* "raw" annotation files are ready to go public
* resolution on #71 
* decision on where to put IAA code 
* (possibly) revision of the readme for additional SWT types

If you want to switch the target branch to a somewhat intermediate "develop" branch for RFB in general, feel free to do so. I just don't think the readme file only isn't enough to go into the `main` branch.

**Comment by keighrim** [comment]
From yesterday's meeting, here's some (interim) decisions: 

> * "raw" annotation files are ready to go public

R2 annotation files are ready.

> * resolution on https://github.com/clamsproject/aapb-annotations/issues/71

(interim) For R2 annotation, after eyeballing on the initial IAA results, we decided to use Gabe's as base and do "union" of two annotation sets to create the first public version gold. 

> * decision on where to put IAA code

The code is being pushed to https://github.com/clamsproject/aapb-annenv-role-filler-binder/tree/iaa_calculation branch. 


> * (possibly) revision of the readme for additional SWT types

We decided a while ago to completely disregard SWT-like subtask from the RFB annotation, so this point shouldn't be relevant any more.

**Review by keighrim — CHANGES_REQUESTED** [review]
Please 
1. add "gold" (by simple merge) (Manual or by writing code? Pick whichever you think the quicker)
2. update readme with documenting (`process.py` section) of the adjudication steps 
3. update the guideline link to the newly formatted document

**Comment by jarumihooi** [comment]
During another conversation, I believe for these two reasons, we decided to hold off on a publicized golds:
1. We decided to use Gabe's raws as uploaded raws for now. 
2. Other tools may have requests for certain formatting of the golds, therefore more might be required during processing. 

Let's scope this issue as starting a readme, documenting the batches, and uploading one of the raws. A new issue can be created for formalizing the golds format and process.py

**Review by keighrim — APPROVED** [review]

**Pull request merged**
