### PR TITLE
#89 --- RFB gold processing

### PR DESCRIPTION
**Pull request by MrSqually**
This PR is to add a `process.py` file for converting a directory of gold JSON annotations into a single CSV file. This satisfies the first two objectives of #89. 

### additions 
+ `role-filler-binding/process.py` 
+ gold files generated from `process.py` on `231117-aapb-annotations-44` data

### discussion before merging 
+ is this a suitable format for the data (newline-separated CSV)?
+ do we want to discard any of the non-RF data from this batch? do we actually want all these duplicates?

### CODE REVIEW

**Comment by keighrim** [comment]
For the second discussion point, I think we should keep the duplicate labels, since they are also human generated (valuable) data that have potential usages.

**Comment by bohJiang12** [comment]
## Implementations
* `process.py`: Updated the script to 
    * export formatted `.csv` files with additional column `SKIPPED` indicating whether a frame is skipped by the human annotator 
    * store each GUID under the protocol required directory `golds`
    * set the `.csv` file as `LF` format (try run `cat -A <csv_file> | less` to see if **only** dollar sign `$` at the end for each line)
* `README.md`: Added description for `process.py` and `golds` directory, especially for how the `ANNOTATIONS` column relates to raw annotations stored in JSON format.
* `requirements.txt`: created my dev environment as required by the document

**Review by keighrim — CHANGES_REQUESTED** [review]
okay, output looks good. Just a few minor thing
- old `csv` gold file now can be deleted
- requirements.txt seems to be too verbose, while there's only one thrid-party library (`clams-utils`) used in the proc.py..?

**Comment by bohJiang12** [comment]
> * requirements.txt seems to be too verbose, while there's only one thrid-party library (`clams-utils`) used in the proc.py..?

In fact, I just exported `pip` installed packages using `pip freeze`, this might show many packages but only `clams_utils` be used. So I'll update them later.

**Review by keighrim — DISMISSED** [review]

**Pull request merged**
