### PR TITLE
adding raw annotation files to SR branch

### PR DESCRIPTION
**Pull request by keighrim**
Starting a PR to merge raw files and batch files to SR readme branch (#66 ), so that all related information stay in a branch. 

(once it's merged, I'd like to suggest to change the batch names from `batch{A,B}-issue-number` to `issue-number-{suffix}` to make them go together under OS file name sortings. For suffixes, how about using more meaningful ones than simple numbering, for example, tight/loose or fine/coarse ?

### CODE REVIEW

**Comment by jarumihooi** [comment]
So, one of the questions is this: Are batches meant to be reused for different things? 
If so, the dense and sparse as part of the name do not describe the batch itself but what it was subsequently used for in creating raw. 
If its not expected, then yes, better naming will make this much clearer. (Or if it doesn't matter if we don't care about how the names will be confusing in future usages for different projects.)

@keighrim

**Comment by keighrim** [comment]
Yes, they are supposed to be re-usable for different training and/or evaluation instances. dense/sparse also is a good suffix pair.

**Comment by jarumihooi** [comment]
> Yes, they are supposed to be re-usable for different training and/or evaluation instances. dense/sparse also is a good suffix pair.

Hi, I want to confirm again: "dense/sparse" is a quality of how the batch was used for SR project specifically AFTER it was created. It does not describe the batch itself. 
Do we want to use this as part of the batch name?

**Comment by keighrim** [comment]
Good point. I completely misread the previous comment. You are right in that the batches are compiled without considering how (on which granularity) they would be annotated. Now I think simple numbering (`A`/`B`) aren't that bad choice for their names.

**Review by jarumihooi — APPROVED** [review]
I believe since this is my branch (and not-main), I can review/accept this PR in. 

batchesB.txt has the additional 42nd GUID that should not be delivered. it is cpb-aacip-516-5m6251gg3j -> this is an accounting error discovered in more exploration of the below dashboard table. Will fix in a future commit. 
https://docs.google.com/spreadsheets/d/1C1s7tJErZL3mEME78oTjaRxhWjD2Ke9pIIKFQcSyM8E/edit#gid=0

**Comment by jarumihooi** [comment]
> Good point. I completely misread the previous comment. You are right in that the batches are compiled without considering how (on which granularity) they would be annotated. Now I think simple numbering (`A`/`B`) aren't that bad choice for their names.
> 
> (I still prefer lower cases `a`/`b` since we have no upper case letters in other batch names so far and I'd like to propose a convention to use lower cases only for naming batches)

Can make this a convention, will write it down for now.

**Pull request merged**
